---
title: "2. Time series graphics"
author: "2.2 Time plots"
date: "OTexts.org/fpp3/"
classoption: aspectratio=169
titlepage: fpp3title.png
titlecolor: fpp3red
toc: false
output:
  binb::monash:
    colortheme: monashwhite
    fig_width: 7.5
    fig_height: 3
    keep_tex: no
    includes:
      in_header: fpp3header.tex
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
source("setup.R")
PBS |>
  filter(ATC2 == "A10") |>
  select(Month, Concession, Type, Cost) |>
  summarise(TotalC = sum(Cost)) |>
  mutate(Cost = TotalC / 1e6) -> a10
```

## Graphics

\fontsize{16}{18}\sf

- Plots allow us to identify:
   - Patterns;
   - Unusual observations;
   - Changes over time;
   - Relationships between variables.

## Time plots
\fontsize{10}{10}\sf

```{r}
a10 |>
  autoplot(Cost) + 
  labs(y = "$ (millions)", title = "Australian antidiabetic drug sales")
```

## Ansett airlines
\fontsize{10}{10}\sf

```{r}
ansett |>
  autoplot(Passengers)
```

## Ansett airlines
\fontsize{10}{10}\sf

```{r}
ansett |>
  filter(Class == "Economy") |>
  autoplot(Passengers)
```

## Ansett airlines
\fontsize{10}{10}\sf

```{r}
ansett |>
  filter(Airports == "MEL-SYD") |>
  autoplot(Passengers)
```

## Ansett airlines
\fontsize{10}{10}\sf

```{r echo=FALSE, fig.height=3.8}
ansett |>
  filter(Airports == "MEL-SYD", Class == "Economy") |>
  mutate(Passengers = Passengers/1000) |> 
  autoplot(Passengers) +
  labs(title = "Ansett airlines economy class", subtitle = "Melbourne-Sydney", 
       y = "Passengers ('000)")
```