---
title: "7. Time series regression models"
author: "7.7 Nonlinear regression"
date: "OTexts.org/fpp3/"
classoption: aspectratio=169
titlepage: fpp3title.png
titlecolor: fpp3red
toc: false
output:
  binb::monash:
    colortheme: monashwhite
    fig_width: 7.5
    fig_height: 3
    keep_tex: no
    includes:
      in_header: fpp3header.tex
---

```{r setup, include=FALSE}
source("setup.R")
```

## Example: Boston marathon winning times

```{r, fig.height=2.6, echo=TRUE}
marathon <- boston_marathon |>
  filter(Event == "Men's open division") |>
  select(-Event) |>
  mutate(Minutes = as.numeric(Time) / 60)
marathon |> autoplot(Minutes) + labs(y = "Winning times in minutes")
```

## Example: Boston marathon winning times

\fontsize{9}{9}\sf

```{r, echo=TRUE}
fit_trends <- marathon |>
  model(
    # Linear trend
    linear = TSLM(Minutes ~ trend()),
    # Exponential trend
    exponential = TSLM(log(Minutes) ~ trend()),
    # Piecewise linear trend
    piecewise = TSLM(Minutes ~ trend(knots = c(1940, 1980)))
  )
```

```{r}
fit_trends
```

## Example: Boston marathon winning times

```{r, echo=TRUE, eval=FALSE, fig.height=2.7}
fit_trends |>
  forecast(h = 10) |>
  autoplot(marathon)
```

```{r, echo=FALSE, message=TRUE, warning=FALSE, fig.height=3}
fc_trends <- fit_trends |> forecast(h = 10)
marathon |>
  autoplot(Minutes) +
  geom_line(
    data = fitted(fit_trends),
    aes(y = .fitted, colour = .model)
  ) +
  autolayer(fc_trends, alpha = 0.5, level = 95) +
  labs(
    y = "Minutes",
    title = "Boston marathon winning times"
  )
```

## Example: Boston marathon winning times

```{r residPiecewise, message=FALSE, warning=FALSE}
fit_trends |>
  select(piecewise) |>
  gg_tsresiduals()
```
