---
title: "9. ARIMA models"
author: "9.8 Forecasting"
date: "OTexts.org/fpp3/"
classoption: aspectratio=169
titlepage: fpp3title.png
titlecolor: fpp3red
toc: false
output:
  binb::monash:
    colortheme: monashwhite
    fig_width: 7.5
    fig_height: 3
    keep_tex: no
    includes:
      in_header: fpp3header.tex
---
```{r setup, include=FALSE}
source("setup.R")
library(patchwork)
library(purrr)
```

## Point forecasts

1. Rearrange ARIMA equation so $y_t$ is on LHS.
2. Rewrite equation by replacing $t$ by $T+h$.
3. On RHS, replace future observations by their forecasts, future errors by zero, and past errors by corresponding residuals.

Start with $h=1$. Repeat for $h=2,3,\dots$.

## Point forecasts
\fontsize{14}{14}\sf

\orange{ARIMA(3,1,1) forecasts: Step 1}
\begin{block}{}
\centerline{$(1-\hat{\phi}_1B -\hat{\phi}_2B^2-\hat{\phi}_3B^3)(1-B) y_t = (1+\hat{\theta}_1B)\varepsilon_{t},$}
\end{block}
\pause\vspace*{-0.9cm}
$$
\left[1-\hat{\phi}_1B -\hat{\phi}_2B^2-\hat{\phi}_3B^3 - B+\hat{\phi}_1B^2 +\hat{\phi}_2B^3+\hat{\phi}_3B^4 \right] y_t = (1+\hat{\theta}_1B)\varepsilon_{t}
$$\pause\vspace*{-0.4cm}
$$
\left[1-(1+\hat{\phi}_1)B +(\hat{\phi}_1-\hat{\phi}_2)B^2 + (\hat{\phi}_2-\hat{\phi}_3)B^3 +\hat{\phi}_3B^4\right] y_t = (1+\hat{\theta}_1B)\varepsilon_{t}
$$\pause\vspace*{-0.2cm}
$$
y_t - (1+\hat{\phi}_1)y_{t-1} +(\hat{\phi}_1-\hat{\phi}_2)y_{t-2} + (\hat{\phi}_2-\hat{\phi}_3)y_{t-3}+\hat{\phi}_3y_{t-4} = \varepsilon_t+\hat{\theta}_1\varepsilon_{t-1}
$$\pause\vspace*{-0.4cm}
$$
y_t = (1+\hat{\phi}_1)y_{t-1} -(\hat{\phi}_1-\hat{\phi}_2)y_{t-2} - (\hat{\phi}_2-\hat{\phi}_3)y_{t-3}-\hat{\phi}_3y_{t-4} + \varepsilon_t+\hat{\theta}_1\varepsilon_{t-1}
$$

## Point forecasts (h=1)
\fontsize{14}{14}\sf

\begin{block}{}
\centerline{$y_t = (1+\hat{\phi}_1)y_{t-1} -(\hat{\phi}_1-\hat{\phi}_2)y_{t-2} - (\hat{\phi}_2-\hat{\phi}_3)y_{t-3} -\hat{\phi}_3y_{t-4} + \varepsilon_t+\hat{\theta}_1\varepsilon_{t-1}$}
\end{block}\pause
\orange{ARIMA(3,1,1) forecasts: Step 2}\vspace*{-0.4cm}
\begin{align*}
y_{T+1} = (1+\hat{\phi}_1)y_{T} -(\hat{\phi}_1-\hat{\phi}_2)y_{T-1} - (\hat{\phi}_2-\hat{\phi}_3)y_{T-2}-\hat{\phi}_3y_{T-3} + \varepsilon_{T+1}+\hat{\theta}_1\varepsilon_{T}
\end{align*}\pause
\orange{ARIMA(3,1,1) forecasts: Step 3}\vspace*{-0.4cm}
\begin{align*}
\hat{y}_{T+1|T} = (1+\hat{\phi}_1)y_{T} -(\hat{\phi}_1-\hat{\phi}_2)y_{T-1} - (\hat{\phi}_2-\hat{\phi}_3)y_{T-2}{} -\hat{\phi}_3y_{T-3} + \hat{\theta}_1 e_{T}
\end{align*}

## Point forecasts (h=2)
\fontsize{14}{14}\sf

\begin{block}{}
\centerline{$y_t = (1+\hat{\phi}_1)y_{t-1} -(\hat{\phi}_1-\hat{\phi}_2)y_{t-2} - (\hat{\phi}_2-\hat{\phi}_3)y_{t-3}-\hat{\phi}_3y_{t-4} + \varepsilon_t+\hat{\theta}_1\varepsilon_{t-1}$}
\end{block}\pause
\orange{ARIMA(3,1,1) forecasts: Step 2}\vspace*{-0.4cm}
\begin{align*}
y_{T+2} = (1+\hat{\phi}_1)y_{T+1} -(\hat{\phi}_1-\hat{\phi}_2)y_{T} - (\hat{\phi}_2-\hat{\phi}_3)y_{T-1} -\hat{\phi}_3y_{T-2} + \varepsilon_{T+2}+\hat{\theta}_1\varepsilon_{T+1}.
\end{align*}\pause
\orange{ARIMA(3,1,1) forecasts: Step 3}\vspace*{-0.4cm}
\begin{align*}
\hat{y}_{T+2|T} = (1+\hat{\phi}_1)\hat{y}_{T+1|T} -(\hat{\phi}_1-\hat{\phi}_2)y_{T} - (\hat{\phi}_2-\hat{\phi}_3)y_{T-1} -\hat{\phi}_3y_{T-2}.
\end{align*}

## Prediction intervals

\fontsize{13}{14}\sf

Assuming $\varepsilon_t\sim N(0,\sigma^2)$

\begin{block}{95\% prediction interval}
\centerline{$\hat{y}_{T+h|T} \pm 1.96\sqrt{v_{T+h|T}}$}
where $v_{T+h|T}$ is estimated forecast variance.
\end{block}\pause\vspace*{-0.2cm}

* $v_{T+1|T}=\hat{\sigma}^2$ for all ARIMA models

\pause

* Multi-step prediction intervals for ARIMA(0,0,$q$):
\centerline{$\displaystyle y_t = \varepsilon_t + \sum_{i=1}^q \hat{\theta}_i \varepsilon_{t-i}.$}
\centerline{$\displaystyle
v_{T|T+h} = \hat{\sigma}^2 \left[ 1 + \sum_{i=1}^{h-1} \hat{\theta}_i^2\right], \qquad\text{for~} h=2,3,\dots.$}

\pause

* Other models beyond scope of this book.

\vspace*{10cm}


## Prediction intervals

* Prediction intervals \orange{increase in size with forecast horizon}.
* Prediction intervals can be difficult to calculate by hand
* Calculations assume residuals are \orange{uncorrelated} and \orange{normally distributed}.
* Prediction intervals tend to be too narrow.
    * the \orange{uncertainty in the parameter estimates} has not been accounted for.
    * \orange{model uncertainty} has not been accounted for.
    * the ARIMA model assumes \orange{historical patterns will not change} during the forecast period.
    * the ARIMA model assumes \orange{uncorrelated future \rlap{errors.}}
